#ifndef SL_COMPONENT_CATALOG_H
#define SL_COMPONENT_CATALOG_H

// APIs present in project
#define SL_CATALOG_APP_ASSERT_PRESENT
#define SL_CATALOG_APP_LOG_PRESENT
#define SL_CATALOG_IOSTREAM_LEUART_PRESENT
#define SL_CATALOG_IOSTREAM_SWO_PRESENT
#define SL_CATALOG_IOSTREAM_UART_PRESENT
#define SL_CATALOG_IOSTREAM_USART_PRESENT
#define SL_CATALOG_MPU_PRESENT
#define SL_CATALOG_MX25_FLASH_SHUTDOWN_PRESENT
#define SL_CATALOG_OPENTHREAD_STACK_PRESENT
#define SL_CATALOG_POWER_SUPPLY_PRESENT
#define SL_CATALOG_PRINTF_PRESENT
#define SL_CATALOG_SENSOR_LIGHT_PRESENT
#define SL_CATALOG_BTN0_PRESENT
#define SL_CATALOG_BTN1_PRESENT
#define SL_CATALOG_SIMPLE_TIMER_PRESENT

#endif // SL_COMPONENT_CATALOG_H
